on:
  workflow_dispatch:

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    runs-on: ubuntu-latest
    # You can use configuration variables with the `vars` context for dynamic jobs
    # environment: ${{ vars.ENVIRONMENT_STAGE }}
    environment: test1
    steps:
    - name: Use variables
      run: |
        $( echo "$ACTION_GITHUB_ENV" | jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' )
        $( echo "$ACTION_GITHUB_VARS" | jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' )
        $( echo "$ACTION_GITHUB_SECRETS" | jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' )
        printenv
      env:
        ACTION_GITHUB_ENV: ${{ toJSON(env) }}
        ACTION_GITHUB_VARS: ${{ toJSON(vars) }}
        ACTION_GITHUB_SECRETS: ${{ toJSON(secrets) }}
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
        OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
        
    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
